### PR TITLE
Add script to quickly switch to development mode

### PR DESCRIPTION
**Pull request by grimpy**

### CODE REVIEW

**Comment by grimpy** [comment]
Nevermind `go generate siteservice/website/website.go` will do the trick.

**Comment by robvanmieghem** [comment]
Cool, kunt ge dat ook even in de contributing.md documenteren?

**Comment by grimpy** [comment]
@robvanmieghem added it to the docs and clarified the diffrence between development mode and production a bit more.

**Comment by robvanmieghem** [comment]
Thanks!

**Pull request merged**
